const express = require("express");
const app = express();

app.use(logger);
app.get("/",(req,res)=>{
    return res.send({name :"Sarfaraz"});
});

app.get("/user",(req,res)=>{
    return res.send("All user")
});

function logger(req,res, next){
    console.log("one");
    console.log("two");
    console.log("three")
    //object is called
    User_A = [{"author":"Florencia","book_name":"Deer, black-tailed","pages":"0.39","published_year":2005},
{"author":"Agnes","book_name":"Boa, emerald green tree","pages":"2.2","published_year":1996},
{"author":"Adolpho","book_name":"American woodcock","pages":"0.44","published_year":1998},
{"author":"Reuben","book_name":"Magpie, black-backed","pages":"0.3.5","published_year":1993},
{"author":"Claresta","book_name":"Pampa gray fox","pages":"0.5.1","published_year":2012},
{"author":"Blondelle","book_name":"Kaffir cat","pages":"1.6","published_year":2008},
{"author":"Jessi","book_name":"Richardson's ground squirrel","pages":"0.81","published_year":2010},
{"author":"Donnie","book_name":"Alligator, mississippi","pages":"0.8.2","published_year":1984},
{"author":"Neile","book_name":"Boar, wild","pages":"0.45","published_year":2010},
{"author":"Baxter","book_name":"Badger, european","pages":"2.2.9","published_year":1999},
{"author":"Zechariah","book_name":"Fox, grey","pages":"3.5.7","published_year":2010},
{"author":"Humberto","book_name":"Giant armadillo","pages":"4.3","published_year":2002},
{"author":"Maynard","book_name":"Raven, cape","pages":"0.8.2","published_year":1996},
{"author":"Urbanus","book_name":"Mourning collared dove","pages":"0.85","published_year":2000},
{"author":"Lotti","book_name":"Kingfisher, malachite","pages":"4.33","published_year":2012},
{"author":"Shirlee","book_name":"Cardinal, red-capped","pages":"0.6.9","published_year":1994},
{"author":"Stoddard","book_name":"Horned rattlesnake","pages":"0.78","published_year":2003},
{"author":"Allistir","book_name":"Skua, great","pages":"4.47","published_year":2009},
{"author":"Laurice","book_name":"Hoopoe, eurasian","pages":"9.25","published_year":1991},
{"author":"Pru","book_name":"Black rhinoceros","pages":"0.56","published_year":2013},
{"author":"Rebekah","book_name":"Chipmunk, least","pages":"0.73","published_year":1996},
{"author":"Fayina","book_name":"Water moccasin","pages":"7.4","published_year":2012},
{"author":"Oran","book_name":"Dabchick","pages":"0.28","published_year":2013},
{"author":"Cynthea","book_name":"Heron, boat-billed","pages":"5.1.0","published_year":2008},
{"author":"Steffen","book_name":"Striped skunk","pages":"0.41","published_year":2008},
{"author":"Lucita","book_name":"Ringtail","pages":"9.7.0","published_year":2011},
{"author":"Corty","book_name":"Armadillo, common long-nosed","pages":"1.0.9","published_year":2011},
{"author":"Stephi","book_name":"Lemur, lesser mouse","pages":"0.73","published_year":1996},
{"author":"Lari","book_name":"Bahama pintail","pages":"1.88","published_year":2004},
{"author":"Demetris","book_name":"Francolin, swainson's","pages":"4.3","published_year":1993},
{"author":"Abeu","book_name":"Roadrunner, greater","pages":"3.2","published_year":2003},
{"author":"Madelaine","book_name":"Common long-nosed armadillo","pages":"7.44","published_year":2006},
{"author":"Mirabelle","book_name":"African skink","pages":"8.36","published_year":1996},
{"author":"Andree","book_name":"Raccoon dog","pages":"0.8.3","published_year":1995},
{"author":"Georgeanne","book_name":"Rhesus macaque","pages":"1.30","published_year":2007},
{"author":"Maren","book_name":"Tailless tenrec","pages":"0.28","published_year":1994},
{"author":"Porter","book_name":"Curlew, black","pages":"0.2.4","published_year":2011},
{"author":"Sandi","book_name":"Leopard","pages":"0.4.4","published_year":2009},
{"author":"Glenda","book_name":"Australian masked owl","pages":"0.25","published_year":2006},
{"author":"Yoko","book_name":"Dog, african wild","pages":"0.7.3","published_year":2003},
{"author":"Laureen","book_name":"Moose","pages":"0.2.4","published_year":1967},
{"author":"Bobbee","book_name":"Blue-tongued skink","pages":"6.87","published_year":2004},
{"author":"Kalie","book_name":"Lion, mountain","pages":"7.3","published_year":2002},
{"author":"Janetta","book_name":"Brown capuchin","pages":"6.1","published_year":2011},
{"author":"Clari","book_name":"Pampa gray fox","pages":"0.21","published_year":2006},
{"author":"Sheelah","book_name":"Lion, australian sea","pages":"6.1.1","published_year":1997},
{"author":"Laurent","book_name":"Malagasy ground boa","pages":"0.28","published_year":1997},
{"author":"Joy","book_name":"Tortoise, galapagos","pages":"0.72","published_year":1996},
{"author":"Pasquale","book_name":"Goldeneye, barrows","pages":"0.43","published_year":2003},
{"author":"Claresta","book_name":"Starling, greater blue-eared","pages":"0.9.0","published_year":1997},
{"author":"Jo-anne","book_name":"Crane, black-crowned","pages":"6.8.9","published_year":1998},
{"author":"Barri","book_name":"Teal, hottentot","pages":"4.8.6","published_year":2001},
{"author":"Reid","book_name":"Sheep, stone","pages":"0.36","published_year":2005},
{"author":"Goldia","book_name":"Violet-crested turaco","pages":"0.73","published_year":1996},
{"author":"Mariejeanne","book_name":"Crane, stanley","pages":"9.78","published_year":2005},
{"author":"Delilah","book_name":"Oriental white-backed vulture","pages":"2.9.4","published_year":2006},
{"author":"Parry","book_name":"Ass, asiatic wild","pages":"5.0","published_year":1994},
{"author":"Ebenezer","book_name":"Miner's cat","pages":"0.7.5","published_year":2012},
{"author":"Melissa","book_name":"Burmese brown mountain tortoise","pages":"0.1.3","published_year":2011},
{"author":"Tiffanie","book_name":"Southern lapwing","pages":"6.8","published_year":2001},
{"author":"Ortensia","book_name":"Wallaby, bennett's","pages":"3.8.9","published_year":2002},
{"author":"Diann","book_name":"Bulbul, african red-eyed","pages":"3.58","published_year":2007},
{"author":"Karla","book_name":"Egyptian vulture","pages":"8.3.8","published_year":2007},
{"author":"Babette","book_name":"Darwin ground finch (unidentified)","pages":"3.5","published_year":2005},
{"author":"Riva","book_name":"Lynx, african","pages":"1.58","published_year":2007},
{"author":"Mamie","book_name":"Red sheep","pages":"0.38","published_year":1994},
{"author":"Carolina","book_name":"Jaeger, long-tailed","pages":"0.6.2","published_year":1996},
{"author":"Audre","book_name":"Cat, miner's","pages":"0.2.3","published_year":2003},
{"author":"Arluene","book_name":"Goose, spur-winged","pages":"0.5.9","published_year":2008},
{"author":"Gerick","book_name":"Canadian river otter","pages":"0.48","published_year":2005},
{"author":"Cort","book_name":"Chilean flamingo","pages":"0.37","published_year":1963},
{"author":"Waylin","book_name":"Cobra, egyptian","pages":"3.4.8","published_year":2010},
{"author":"Adriana","book_name":"Flamingo, chilean","pages":"3.28","published_year":1993},
{"author":"Delbert","book_name":"Greater adjutant stork","pages":"0.91","published_year":2005},
{"author":"Ezri","book_name":"Wombat, common","pages":"0.39","published_year":2011},
{"author":"Nicola","book_name":"Jackal, black-backed","pages":"5.45","published_year":2005},
{"author":"Kaspar","book_name":"Common raccoon","pages":"0.3.7","published_year":1992},
{"author":"Bobbette","book_name":"Rhesus macaque","pages":"0.79","published_year":2007},
{"author":"Wilton","book_name":"Wallaroo, common","pages":"1.0.2","published_year":2002},
{"author":"Montgomery","book_name":"Javan gold-spotted mongoose","pages":"0.6.5","published_year":1992},
{"author":"Gusta","book_name":"Godwit, hudsonian","pages":"0.31","published_year":2003},
{"author":"Davita","book_name":"Starling, greater blue-eared","pages":"6.2","published_year":1992},
{"author":"Munroe","book_name":"Mongoose, banded","pages":"5.3.2","published_year":2012},
{"author":"Gwyneth","book_name":"Blue peacock","pages":"6.1.5","published_year":2004},
{"author":"Atlanta","book_name":"Tortoise, indian star","pages":"7.1","published_year":2004},
{"author":"Derby","book_name":"Ground legaan","pages":"6.44","published_year":2006},
{"author":"Addie","book_name":"Porcupine, indian","pages":"5.09","published_year":1999},
{"author":"Caty","book_name":"Duiker, gray","pages":"6.5","published_year":2012},
{"author":"Brad","book_name":"Honey badger","pages":"0.49","published_year":2001},
{"author":"Sigfried","book_name":"Vicuna","pages":"8.7","published_year":2006},
{"author":"Carmen","book_name":"Woodpecker, downy","pages":"2.20","published_year":2009},
{"author":"Clemmy","book_name":"Colobus, magistrate black","pages":"2.64","published_year":2009},
{"author":"Izabel","book_name":"Barasingha deer","pages":"9.3.9","published_year":1996},
{"author":"Emmott","book_name":"Chameleon (unidentified)","pages":"6.0","published_year":2008},
{"author":"Bennie","book_name":"Great egret","pages":"0.79","published_year":2012},
{"author":"Devon","book_name":"Rhea, common","pages":"4.9.0","published_year":1992},
{"author":"Page","book_name":"Magistrate black colobus","pages":"9.3","published_year":2009},
{"author":"Quinn","book_name":"Pale white-eye","pages":"0.4.4","published_year":2007},
{"author":"Agretha","book_name":"Eastern boa constrictor","pages":"8.55","published_year":2008},
{"author":"Garwood","book_name":"Starling, cape","pages":"0.96","published_year":2005},
{"author":"Rosina","book_name":"Masked booby","pages":"0.9.9","published_year":2005},
{"author":"Hendrika","book_name":"Albatross, galapagos","pages":"0.4.2","published_year":1997},
{"author":"Kristoffer","book_name":"Ferret, black-footed","pages":"0.48","published_year":2008},
{"author":"Talia","book_name":"Galapagos tortoise","pages":"5.09","published_year":2007},
{"author":"Antin","book_name":"Collared lizard","pages":"0.5.7","published_year":2003},
{"author":"Jesselyn","book_name":"Oryx, fringe-eared","pages":"4.6.2","published_year":2006},
{"author":"Cy","book_name":"Malay squirrel (unidentified)","pages":"1.26","published_year":2005},
{"author":"Dunstan","book_name":"Elegant crested tinamou","pages":"0.85","published_year":1988},
{"author":"My","book_name":"Burmese black mountain tortoise","pages":"9.58","published_year":1999},
{"author":"Adan","book_name":"Black bear","pages":"0.87","published_year":1999},
{"author":"Florry","book_name":"Bear, polar","pages":"4.43","published_year":2004},
{"author":"Bret","book_name":"Dragon, netted rock","pages":"1.26","published_year":2012},
{"author":"Kenneth","book_name":"Cobra, cape","pages":"1.8","published_year":2012},
{"author":"Kirbie","book_name":"Otter, african clawless","pages":"0.2.6","published_year":1994},
{"author":"Yuma","book_name":"Frilled lizard","pages":"7.37","published_year":1984},
{"author":"Sloane","book_name":"King vulture","pages":"0.7.6","published_year":2001},
{"author":"Jacquelin","book_name":"Genet, common","pages":"4.37","published_year":2004},
{"author":"Kristoforo","book_name":"Small-toothed palm civet","pages":"0.7.0","published_year":2002},
{"author":"Kissie","book_name":"Duiker, common","pages":"8.0.3","published_year":2007},
{"author":"Wilona","book_name":"Black-winged stilt","pages":"0.8.5","published_year":2007},
{"author":"Drake","book_name":"Red-capped cardinal","pages":"0.71","published_year":2009},
{"author":"Glenna","book_name":"Sheathbill, snowy","pages":"1.14","published_year":2006},
{"author":"Agustin","book_name":"Pig-tailed macaque","pages":"5.00","published_year":2010},
{"author":"Laural","book_name":"Little cormorant","pages":"0.64","published_year":2012},
{"author":"Vincenty","book_name":"Roe deer","pages":"0.6.8","published_year":1996},
{"author":"Moses","book_name":"Yellow-necked spurfowl","pages":"2.9.1","published_year":1999},
{"author":"Cass","book_name":"Prairie falcon","pages":"0.53","published_year":1993},
{"author":"Elsworth","book_name":"Common seal","pages":"5.3.6","published_year":2001},
{"author":"Fawne","book_name":"Fox, cape","pages":"0.8.3","published_year":2003},
{"author":"Lenee","book_name":"Badger, european","pages":"3.3.2","published_year":1999},
{"author":"Constantino","book_name":"Royal tern","pages":"8.5.7","published_year":2008},
{"author":"Gabriel","book_name":"Eagle, crowned","pages":"0.17","published_year":1962},
{"author":"Alane","book_name":"Indian leopard","pages":"0.3.5","published_year":2007},
{"author":"Aristotle","book_name":"Armadillo, nine-banded","pages":"0.17","published_year":2008},
{"author":"Lorenza","book_name":"Barbet, black-collared","pages":"0.5.9","published_year":2005},
{"author":"Cari","book_name":"Owl, madagascar hawk","pages":"6.0","published_year":2003},
{"author":"Onfroi","book_name":"Porcupine, tree","pages":"0.1.2","published_year":2005},
{"author":"Briney","book_name":"Clark's nutcracker","pages":"4.0","published_year":1986},
{"author":"Any","book_name":"Red-billed tropic bird","pages":"0.8.3","published_year":1994},
{"author":"Gwenette","book_name":"Duiker, gray","pages":"6.1","published_year":2011},
{"author":"Ambrosio","book_name":"Eagle owl (unidentified)","pages":"0.44","published_year":2008},
{"author":"Verne","book_name":"Two-banded monitor","pages":"8.1","published_year":1993},
{"author":"Sauveur","book_name":"Palm squirrel","pages":"9.39","published_year":2011},
{"author":"Gilles","book_name":"Lion, california sea","pages":"0.22","published_year":1994},
{"author":"Giulia","book_name":"Golden eagle","pages":"0.2.5","published_year":1984},
{"author":"Jere","book_name":"Pigeon, wood","pages":"0.98","published_year":2007},
{"author":"Travis","book_name":"Heron, green","pages":"9.8.4","published_year":1984},
{"author":"Slade","book_name":"Indian leopard","pages":"0.6.8","published_year":2006},
{"author":"Ben","book_name":"Water monitor","pages":"0.57","published_year":2001},
{"author":"Collie","book_name":"Robin, kalahari scrub","pages":"4.8.6","published_year":1997},
{"author":"Cristy","book_name":"Madagascar hawk owl","pages":"3.1.9","published_year":2000},
{"author":"Amelita","book_name":"Owl, burrowing","pages":"0.30","published_year":2011},
{"author":"Zacharias","book_name":"Northern elephant seal","pages":"0.24","published_year":2010},
{"author":"Correy","book_name":"Indian jackal","pages":"1.2","published_year":1988},
{"author":"Joellyn","book_name":"Seven-banded armadillo","pages":"1.5","published_year":2005},
{"author":"Brande","book_name":"Seven-banded armadillo","pages":"0.8.6","published_year":1995},
{"author":"Karee","book_name":"Python, carpet","pages":"5.3","published_year":2008},
{"author":"Margarette","book_name":"Western grey kangaroo","pages":"9.0","published_year":1998},
{"author":"Hyacinth","book_name":"Green vine snake","pages":"0.86","published_year":1991},
{"author":"Nat","book_name":"Rhesus monkey","pages":"1.02","published_year":1997},
{"author":"Butch","book_name":"Vulture, white-rumped","pages":"0.32","published_year":1993},
{"author":"Gracie","book_name":"Thirteen-lined squirrel","pages":"4.75","published_year":1998},
{"author":"Dwayne","book_name":"Turkey, common","pages":"6.1","published_year":2003},
{"author":"Cariotta","book_name":"Mexican beaded lizard","pages":"7.94","published_year":1992},
{"author":"Amelina","book_name":"Brown brocket","pages":"0.8.8","published_year":2004},
{"author":"Gal","book_name":"White-fronted bee-eater","pages":"0.79","published_year":1996},
{"author":"Robena","book_name":"Ferret, black-footed","pages":"4.8.8","published_year":2008},
{"author":"Rosaleen","book_name":"Greater adjutant stork","pages":"9.9.6","published_year":2005},
{"author":"Perle","book_name":"Steenbuck","pages":"1.3.4","published_year":1998},
{"author":"Adan","book_name":"Burmese black mountain tortoise","pages":"6.09","published_year":2007},
{"author":"Codi","book_name":"Dog, raccoon","pages":"2.8","published_year":1991},
{"author":"Anna-maria","book_name":"Quoll, spotted-tailed","pages":"0.4.9","published_year":1992},
{"author":"Nathalia","book_name":"Jackal, silver-backed","pages":"4.8.4","published_year":1994},
{"author":"Ashley","book_name":"Black-capped capuchin","pages":"8.9.1","published_year":1993},
{"author":"Hagan","book_name":"Desert tortoise","pages":"7.02","published_year":2011},
{"author":"Marylin","book_name":"Gecko (unidentified)","pages":"7.44","published_year":2001},
{"author":"Ginnie","book_name":"Constrictor, eastern boa","pages":"8.09","published_year":2000},
{"author":"Lovell","book_name":"Mountain lion","pages":"0.85","published_year":2007},
{"author":"Nerta","book_name":"Cobra, cape","pages":"0.11","published_year":2010},
{"author":"Iormina","book_name":"Partridge, coqui","pages":"0.63","published_year":1999},
{"author":"Leese","book_name":"Kongoni","pages":"0.3.3","published_year":1999},
{"author":"Ivy","book_name":"Tsessebe","pages":"0.8.7","published_year":2008},
{"author":"Dotty","book_name":"Fox, grey","pages":"9.1","published_year":1995},
{"author":"Clari","book_name":"Frogmouth, tawny","pages":"1.4","published_year":2004},
{"author":"Glen","book_name":"Spotted hyena","pages":"0.3.0","published_year":1985},
{"author":"Noam","book_name":"Javan gold-spotted mongoose","pages":"0.51","published_year":2007},
{"author":"Conan","book_name":"Seal, common","pages":"0.3.1","published_year":2011},
{"author":"Eric","book_name":"Bear, american black","pages":"0.22","published_year":1995},
{"author":"Tybie","book_name":"Woylie","pages":"0.2.2","published_year":2012},
{"author":"Reina","book_name":"Lesser flamingo","pages":"0.87","published_year":2011},
{"author":"Rooney","book_name":"Swainson's francolin","pages":"4.3","published_year":1996},
{"author":"Yevette","book_name":"Owl, great horned","pages":"0.32","published_year":2001},
{"author":"Kirstyn","book_name":"Macaque, rhesus","pages":"0.1.0","published_year":2011},
{"author":"Phillis","book_name":"Ground monitor (unidentified)","pages":"3.45","published_year":2007},
{"author":"Vanessa","book_name":"Squirrel, smith's bush","pages":"0.8.9","published_year":1993},
{"author":"Osborn","book_name":"Bushbuck","pages":"1.2","published_year":1996},
{"author":"Pat","book_name":"Black-fronted bulbul","pages":"0.9.6","published_year":2004},
{"author":"Lelia","book_name":"Buffalo, african","pages":"2.83","published_year":2013},
{"author":"Shadow","book_name":"European shelduck","pages":"2.3","published_year":1995},
{"author":"Peyter","book_name":"Robin, kalahari scrub","pages":"3.0","published_year":2006},
{"author":"Coral","book_name":"Phalarope, red","pages":"9.37","published_year":2011},
{"author":"Lalo","book_name":"Heron, little","pages":"5.7.4","published_year":1992},
{"author":"Rouvin","book_name":"Tern, white-winged","pages":"0.27","published_year":2008},
{"author":"Carney","book_name":"Rhea, gray","pages":"0.9.8","published_year":2009},
{"author":"Gae","book_name":"Gazer, sun","pages":"0.7.3","published_year":2005},
{"author":"Ian","book_name":"Agouti","pages":"1.4.6","published_year":2006},
{"author":"Dominik","book_name":"Cuis","pages":"0.5.2","published_year":2010},
{"author":"Tatiana","book_name":"Bear, grizzly","pages":"8.53","published_year":2012},
{"author":"Bancroft","book_name":"Brush-tailed bettong","pages":"9.54","published_year":2006},
{"author":"Phelia","book_name":"White-winged tern","pages":"0.63","published_year":2010},
{"author":"Benedict","book_name":"Rhesus monkey","pages":"0.7.0","published_year":2002},
{"author":"Raimundo","book_name":"Mountain goat","pages":"0.9.5","published_year":1994},
{"author":"Carlina","book_name":"South American sea lion","pages":"0.21","published_year":2007},
{"author":"Gannon","book_name":"Ass, asiatic wild","pages":"6.1.6","published_year":1997},
{"author":"Ricky","book_name":"African lynx","pages":"6.6","published_year":1975},
{"author":"Yorgo","book_name":"Sandpiper, spotted wood","pages":"4.36","published_year":2000},
{"author":"Chip","book_name":"Long-nosed bandicoot","pages":"1.00","published_year":1966},
{"author":"Ethelred","book_name":"Swan, black","pages":"0.7.1","published_year":1995},
{"author":"Holly","book_name":"Collared lizard","pages":"0.6.7","published_year":1995},
{"author":"Zacherie","book_name":"Sandhill crane","pages":"0.62","published_year":2007},
{"author":"Leonora","book_name":"White-rumped vulture","pages":"4.66","published_year":1993},
{"author":"Free","book_name":"Long-crested hawk eagle","pages":"1.64","published_year":1994},
{"author":"Abe","book_name":"Goldeneye, common","pages":"8.1","published_year":2007},
{"author":"Hazel","book_name":"Possum, pygmy","pages":"9.63","published_year":2005},
{"author":"Ebony","book_name":"Lark, horned","pages":"8.9.2","published_year":2010},
{"author":"Ase","book_name":"Lizard, desert spiny","pages":"0.70","published_year":2002},
{"author":"Harmonie","book_name":"Bird, magnificent frigate","pages":"0.1.7","published_year":2010},
{"author":"Tamera","book_name":"Dama wallaby","pages":"9.6.5","published_year":1997},
{"author":"Noble","book_name":"Northern phalarope","pages":"6.51","published_year":1992},
{"author":"Aggi","book_name":"Grenadier, common","pages":"4.77","published_year":2008},
{"author":"Pincus","book_name":"Silver gull","pages":"0.7.0","published_year":2012},
{"author":"Luisa","book_name":"Rock dove","pages":"5.47","published_year":2002},
{"author":"Addy","book_name":"Lesser masked weaver","pages":"9.86","published_year":2009},
{"author":"Gretal","book_name":"American racer","pages":"3.17","published_year":2003},
{"author":"Layney","book_name":"Brown pelican","pages":"9.3","published_year":1993},
{"author":"Shanta","book_name":"Bald eagle","pages":"1.5.8","published_year":2008},
{"author":"Cull","book_name":"Skink, blue-tongued","pages":"1.0","published_year":2012},
{"author":"Joannes","book_name":"Water legaan","pages":"1.4","published_year":2005},
{"author":"Rupert","book_name":"Kingfisher, white-throated","pages":"5.8.6","published_year":1993},
{"author":"Annetta","book_name":"Puku","pages":"0.8.5","published_year":2008},
{"author":"Gabriellia","book_name":"Agile wallaby","pages":"4.59","published_year":2011},
{"author":"Hendrik","book_name":"Indian leopard","pages":"4.80","published_year":2011},
{"author":"Gustaf","book_name":"Red deer","pages":"0.47","published_year":2005},
{"author":"Birk","book_name":"Mallard","pages":"9.29","published_year":2006},
{"author":"Bartie","book_name":"Bulbul, black-eyed","pages":"0.6.1","published_year":1995},
{"author":"Valencia","book_name":"Kongoni","pages":"0.60","published_year":1960},
{"author":"Deeyn","book_name":"Grizzly bear","pages":"7.6","published_year":1994},
{"author":"Kiley","book_name":"Tsessebe","pages":"7.4","published_year":2003},
{"author":"Elspeth","book_name":"Hornbill, red-billed","pages":"5.3.9","published_year":1994},
{"author":"Baird","book_name":"Black-tailed deer","pages":"2.4.3","published_year":2004},
{"author":"Ema","book_name":"Spectacled caiman","pages":"0.7.1","published_year":1990},
{"author":"Anallese","book_name":"Racer, american","pages":"0.54","published_year":2010},
{"author":"Carola","book_name":"Olive baboon","pages":"1.8.1","published_year":2012},
{"author":"Robert","book_name":"Lourie, grey","pages":"0.7.9","published_year":1995},
{"author":"Alberto","book_name":"Arctic lemming","pages":"5.67","published_year":1995},
{"author":"Zonnya","book_name":"Bird, black-throated butcher","pages":"2.0.3","published_year":2013},
{"author":"Steven","book_name":"Gull, swallow-tail","pages":"5.0","published_year":1983},
{"author":"Sonny","book_name":"Barbet, black-collared","pages":"0.9.5","published_year":2004},
{"author":"Rosanna","book_name":"Crested bunting","pages":"0.73","published_year":2006},
{"author":"Georg","book_name":"Baboon, gelada","pages":"3.51","published_year":1989},
{"author":"Morry","book_name":"Black swan","pages":"7.4.9","published_year":2012},
{"author":"Ethyl","book_name":"Scarlet macaw","pages":"0.6.7","published_year":2003},
{"author":"Hedda","book_name":"Tinamou, elegant crested","pages":"9.02","published_year":1997},
{"author":"Ricky","book_name":"Red-headed woodpecker","pages":"0.19","published_year":2000},
{"author":"Darci","book_name":"Pheasant, ring-necked","pages":"1.74","published_year":1996},
{"author":"Janey","book_name":"Wildebeest, blue","pages":"0.43","published_year":2006},
{"author":"Fern","book_name":"Dove, galapagos","pages":"0.12","published_year":2005},
{"author":"Margaux","book_name":"Madagascar fruit bat","pages":"1.16","published_year":2012},
{"author":"Bernete","book_name":"Stork, white-necked","pages":"3.2.3","published_year":1990},
{"author":"Rosalyn","book_name":"Australian brush turkey","pages":"0.43","published_year":2007},
{"author":"Albrecht","book_name":"Bulbul, african red-eyed","pages":"6.5","published_year":2003},
{"author":"Kimberley","book_name":"Campo flicker","pages":"6.64","published_year":2007},
{"author":"Eleanor","book_name":"Red and blue macaw","pages":"0.3.3","published_year":2004},
{"author":"Rivy","book_name":"Whale, southern right","pages":"3.2","published_year":2002},
{"author":"Henrik","book_name":"Jackal, indian","pages":"8.0","published_year":2003},
{"author":"Michele","book_name":"Raccoon, crab-eating","pages":"7.5.0","published_year":1988},
{"author":"Teddy","book_name":"Waxbill, black-cheeked","pages":"9.24","published_year":2009},
{"author":"Neddy","book_name":"Springhare","pages":"7.83","published_year":2012},
{"author":"Glen","book_name":"Reedbuck, bohor","pages":"0.39","published_year":2002},
{"author":"Teador","book_name":"Bulbul, black-fronted","pages":"0.5.4","published_year":1992},
{"author":"May","book_name":"Dove, emerald-spotted wood","pages":"0.46","published_year":2002},
{"author":"Fielding","book_name":"Trumpeter, dark-winged","pages":"0.78","published_year":2010},
{"author":"Marguerite","book_name":"Tropical buckeye butterfly","pages":"9.9.1","published_year":1993},
{"author":"Rora","book_name":"Eagle, tawny","pages":"0.3.1","published_year":2007},
{"author":"Shena","book_name":"North American red fox","pages":"1.1","published_year":1995},
{"author":"Grata","book_name":"Brown antechinus","pages":"0.8.1","published_year":2010},
{"author":"Jarred","book_name":"Lemming, arctic","pages":"0.3.9","published_year":2013},
{"author":"Noby","book_name":"Hare, arctic","pages":"8.5","published_year":2008},
{"author":"Ahmad","book_name":"Chilean flamingo","pages":"0.70","published_year":2001},
{"author":"Darren","book_name":"Feathertail glider","pages":"0.9.4","published_year":2008},
{"author":"Morna","book_name":"Loris, slender","pages":"0.6.3","published_year":2010},
{"author":"Jory","book_name":"Koala","pages":"0.59","published_year":2003},
{"author":"Moore","book_name":"Wolf, timber","pages":"6.27","published_year":1997},
{"author":"Biron","book_name":"Lesser mouse lemur","pages":"0.54","published_year":2007},
{"author":"Martainn","book_name":"White-necked raven","pages":"4.5.6","published_year":2002},
{"author":"Evelin","book_name":"Rat, arboral spiny","pages":"0.3.9","published_year":2007},
{"author":"Nollie","book_name":"Lava gull","pages":"3.9","published_year":1995},
{"author":"Darlleen","book_name":"Heron, goliath","pages":"0.16","published_year":2011},
{"author":"Lurette","book_name":"Roadrunner, greater","pages":"0.26","published_year":2012},
{"author":"Kean","book_name":"Asian water dragon","pages":"0.7.7","published_year":2001},
{"author":"Conrade","book_name":"Whip-tailed wallaby","pages":"9.56","published_year":1984},
{"author":"Jodi","book_name":"Tiger","pages":"0.23","published_year":1994},
{"author":"Doralyn","book_name":"Deer, mule","pages":"9.9","published_year":2010},
{"author":"Cecilia","book_name":"Puffin, horned","pages":"0.12","published_year":2011},
{"author":"Sharai","book_name":"Cape cobra","pages":"6.1","published_year":2003},
{"author":"Dale","book_name":"Parakeet, rose-ringed","pages":"0.3.3","published_year":2012},
{"author":"Edy","book_name":"Fox, crab-eating","pages":"0.9.1","published_year":2003},
{"author":"Kyla","book_name":"Green heron","pages":"0.2.6","published_year":1993},
{"author":"Prent","book_name":"Miner's cat","pages":"0.2.0","published_year":1991},
{"author":"Di","book_name":"Ringtail, common","pages":"0.63","published_year":2010},
{"author":"Teodorico","book_name":"Lion, african","pages":"1.8.9","published_year":2008},
{"author":"Addison","book_name":"Langur, common","pages":"1.3","published_year":2006},
{"author":"Tanya","book_name":"Lapwing, southern","pages":"0.44","published_year":2005},
{"author":"Tedra","book_name":"Rattlesnake, horned","pages":"7.7.3","published_year":1987},
{"author":"Lucinda","book_name":"Marshbird, brown and yellow","pages":"0.1.1","published_year":1993},
{"author":"Tobe","book_name":"Cockatoo, sulfur-crested","pages":"2.1.0","published_year":1988},
{"author":"Burl","book_name":"African skink","pages":"0.14","published_year":2008},
{"author":"Lettie","book_name":"Mongoose, eastern dwarf","pages":"4.7","published_year":1991},
{"author":"Gwyneth","book_name":"Southern lapwing","pages":"0.52","published_year":1992},
{"author":"Efrem","book_name":"Legaan, ground","pages":"1.94","published_year":1999},
{"author":"Claire","book_name":"Bunting, crested","pages":"0.6.9","published_year":2007},
{"author":"Lyssa","book_name":"Eurasian hoopoe","pages":"4.2","published_year":2002},
{"author":"Edee","book_name":"Ibis, puna","pages":"5.22","published_year":2010},
{"author":"Orin","book_name":"Coot, red-knobbed","pages":"0.12","published_year":2007},
{"author":"Kelci","book_name":"Tiger","pages":"5.4.6","published_year":1999},
{"author":"Katya","book_name":"White stork","pages":"4.3.8","published_year":2005},
{"author":"Ralf","book_name":"Indian jackal","pages":"0.85","published_year":2010},
{"author":"Shaylah","book_name":"Lesser masked weaver","pages":"4.9","published_year":1994},
{"author":"Eleni","book_name":"Magpie, black-backed","pages":"4.8.6","published_year":2007},
{"author":"Ulises","book_name":"Goldeneye, common","pages":"0.4.5","published_year":1997},
{"author":"Francesca","book_name":"Sidewinder","pages":"0.6.7","published_year":2000},
{"author":"Katha","book_name":"Southern right whale","pages":"3.8","published_year":1993},
{"author":"Danell","book_name":"Reedbuck, bohor","pages":"0.1.6","published_year":1996},
{"author":"Felic","book_name":"Tortoise, asian foreset","pages":"5.2","published_year":2003},
{"author":"Clerissa","book_name":"Hawk, ferruginous","pages":"5.30","published_year":1996},
{"author":"Sinclare","book_name":"Giant anteater","pages":"0.6.5","published_year":1995},
{"author":"Veradis","book_name":"Gelada baboon","pages":"0.90","published_year":2009},
{"author":"Phyllis","book_name":"Puma, south american","pages":"9.1.2","published_year":1991},
{"author":"Evangelia","book_name":"Pelican, brown","pages":"7.09","published_year":2008},
{"author":"Kaela","book_name":"Goldeneye, barrows","pages":"3.9.3","published_year":2006},
{"author":"Den","book_name":"Slender loris","pages":"7.4.9","published_year":2010},
{"author":"Amalia","book_name":"Verreaux's sifaka","pages":"0.66","published_year":2012},
{"author":"Gabriellia","book_name":"Gambel's quail","pages":"1.93","published_year":1997},
{"author":"Julius","book_name":"Great skua","pages":"6.9.5","published_year":2008},
{"author":"Merle","book_name":"Red-necked wallaby","pages":"0.5.7","published_year":2008},
{"author":"Rea","book_name":"Gull, lava","pages":"3.3.8","published_year":1993},
{"author":"Norah","book_name":"Sloth, pale-throated three-toed","pages":"6.6","published_year":1988},
{"author":"Elna","book_name":"Woodpecker, red-headed","pages":"2.4","published_year":2008},
{"author":"Peterus","book_name":"Deer, roe","pages":"0.6.6","published_year":1963},
{"author":"Wilone","book_name":"Squirrel, grey-footed","pages":"7.5","published_year":2003},
{"author":"Gilbertine","book_name":"Lizard, blue-tongued","pages":"0.23","published_year":2003},
{"author":"Noe","book_name":"Bird, black-throated butcher","pages":"6.4","published_year":1989},
{"author":"Florina","book_name":"Reindeer","pages":"0.43","published_year":1994},
{"author":"Renado","book_name":"Dragon, asian water","pages":"3.0","published_year":2000},
{"author":"Merrily","book_name":"European stork","pages":"8.60","published_year":2008},
{"author":"Meara","book_name":"Oribi","pages":"0.9.0","published_year":1989},
{"author":"Gertruda","book_name":"Salmon, sockeye","pages":"0.3.9","published_year":2007},
{"author":"Bird","book_name":"Bear, black","pages":"9.1.9","published_year":2012},
{"author":"Eba","book_name":"Tenrec, tailless","pages":"9.52","published_year":2003},
{"author":"Urbain","book_name":"Collared lizard","pages":"9.35","published_year":1959},
{"author":"Godwin","book_name":"Agile wallaby","pages":"4.8.3","published_year":1986},
{"author":"Charmane","book_name":"Fringe-eared oryx","pages":"8.66","published_year":2010},
{"author":"Bamby","book_name":"Red howler monkey","pages":"0.6.4","published_year":1997},
{"author":"Emery","book_name":"Yellow-throated sandgrouse","pages":"3.13","published_year":1971},
{"author":"Alex","book_name":"Common langur","pages":"0.67","published_year":2009},
{"author":"Arvin","book_name":"Lemming, collared","pages":"0.29","published_year":2004},
{"author":"Harry","book_name":"Shelduck, common","pages":"9.1","published_year":1994},
{"author":"Lorinda","book_name":"Galapagos mockingbird","pages":"9.7.0","published_year":1996},
{"author":"Kathryn","book_name":"Eurasian beaver","pages":"8.5.9","published_year":2011},
{"author":"Hieronymus","book_name":"Crested screamer","pages":"6.15","published_year":2010},
{"author":"Fairfax","book_name":"Lion, southern sea","pages":"6.27","published_year":1998},
{"author":"Redd","book_name":"Turkey, common","pages":"0.47","published_year":1986},
{"author":"Corrie","book_name":"Turtle (unidentified)","pages":"0.86","published_year":2005},
{"author":"Franciskus","book_name":"Little cormorant","pages":"3.8","published_year":2002},
{"author":"Maximilien","book_name":"Fat-tailed dunnart","pages":"7.3.5","published_year":2012},
{"author":"Devy","book_name":"Water legaan","pages":"3.22","published_year":1989},
{"author":"Olin","book_name":"Woodpecker, red-headed","pages":"1.84","published_year":1998},
{"author":"Brandise","book_name":"African skink","pages":"0.80","published_year":2009},
{"author":"Regen","book_name":"Seal, northern elephant","pages":"1.2","published_year":1980},
{"author":"Curran","book_name":"Cat, civet","pages":"0.1.5","published_year":2006},
{"author":"Billy","book_name":"Impala","pages":"7.8.9","published_year":1998},
{"author":"Kaylyn","book_name":"Moose","pages":"0.6.2","published_year":2004},
{"author":"Clemens","book_name":"Cat, toddy","pages":"0.6.4","published_year":1986},
{"author":"Gerladina","book_name":"Black-crowned night heron","pages":"5.9","published_year":2012},
{"author":"Nicolas","book_name":"Fox, asian red","pages":"0.8.5","published_year":1995},
{"author":"Carson","book_name":"Asian openbill","pages":"0.54","published_year":2007},
{"author":"Marlane","book_name":"Nighthawk, common","pages":"9.0","published_year":2000},
{"author":"Gillian","book_name":"Asian openbill","pages":"0.90","published_year":2008},
{"author":"Immanuel","book_name":"Gerbil (unidentified)","pages":"0.3.1","published_year":2010},
{"author":"Jourdain","book_name":"Baboon, savanna","pages":"6.3.8","published_year":1992},
{"author":"Eleonora","book_name":"Four-striped grass mouse","pages":"8.5","published_year":2002},
{"author":"Smitty","book_name":"Otter, african clawless","pages":"3.6","published_year":1990},
{"author":"Merrili","book_name":"Snake, western patch-nosed","pages":"3.5","published_year":2011},
{"author":"Roy","book_name":"King vulture","pages":"0.3.3","published_year":2000},
{"author":"Trey","book_name":"Red hartebeest","pages":"0.7.7","published_year":2005},
{"author":"Ailee","book_name":"Andean goose","pages":"6.7.8","published_year":2001},
{"author":"Shelby","book_name":"Iguana, common green","pages":"9.4","published_year":1993},
{"author":"Avril","book_name":"Musk ox","pages":"3.7","published_year":1977},
{"author":"Meir","book_name":"Long-tailed jaeger","pages":"0.59","published_year":1994},
{"author":"Keeley","book_name":"Civet (unidentified)","pages":"0.71","published_year":1998},
{"author":"Jacklin","book_name":"Seal, harbor","pages":"5.8.7","published_year":2000},
{"author":"Maxy","book_name":"Robin, white-throated","pages":"7.40","published_year":2012},
{"author":"Hank","book_name":"Swallow (unidentified)","pages":"4.8","published_year":2011},
{"author":"Vidovic","book_name":"Rhea, greater","pages":"4.1.8","published_year":1992},
{"author":"Ethel","book_name":"Civet, common palm","pages":"8.6.3","published_year":1984},
{"author":"Normy","book_name":"Cat, miner's","pages":"0.83","published_year":2012},
{"author":"Harmony","book_name":"Worm snake (unidentified)","pages":"0.1.4","published_year":2007},
{"author":"Ezri","book_name":"Dragonfly, russian","pages":"0.5.8","published_year":1990},
{"author":"Perceval","book_name":"Blue catfish","pages":"0.3.1","published_year":1986},
{"author":"Filberte","book_name":"African wild cat","pages":"1.47","published_year":2013},
{"author":"Jaquelyn","book_name":"Cormorant, large","pages":"0.3.4","published_year":1991},
{"author":"Junina","book_name":"African fish eagle","pages":"6.5.8","published_year":1991},
{"author":"Durand","book_name":"Vulture, oriental white-backed","pages":"7.1.0","published_year":1992},
{"author":"Pascale","book_name":"Yellow-brown sungazer","pages":"7.1.1","published_year":1990},
{"author":"Baryram","book_name":"Greater roadrunner","pages":"7.99","published_year":2011},
{"author":"Keely","book_name":"Black bear","pages":"0.8.7","published_year":2010},
{"author":"Alicea","book_name":"Sage hen","pages":"0.8.9","published_year":2006},
{"author":"Aline","book_name":"Woodrat (unidentified)","pages":"0.56","published_year":1998},
{"author":"Claudine","book_name":"Dragon, netted rock","pages":"0.64","published_year":2010},
{"author":"Garvey","book_name":"Goose, andean","pages":"0.83","published_year":2002},
{"author":"Emmy","book_name":"Heron, gray","pages":"0.61","published_year":1999},
{"author":"Lonnie","book_name":"Russian dragonfly","pages":"3.0","published_year":2009},
{"author":"Iain","book_name":"Pied crow","pages":"0.37","published_year":2011},
{"author":"Nil","book_name":"Turaco, violet-crested","pages":"1.1.8","published_year":2013},
{"author":"Jeniece","book_name":"Northern elephant seal","pages":"7.95","published_year":1996},
{"author":"Jere","book_name":"Blackish oystercatcher","pages":"0.4.3","published_year":2003},
{"author":"Ethan","book_name":"Heron, black-crowned night","pages":"7.2.3","published_year":1994},
{"author":"Antin","book_name":"Bengal vulture","pages":"6.18","published_year":2007},
{"author":"Helen-elizabeth","book_name":"Heron, black-crowned night","pages":"9.1.8","published_year":2009},
{"author":"Kirby","book_name":"Hartebeest, coke's","pages":"2.6","published_year":1990},
{"author":"Gisele","book_name":"Desert kangaroo rat","pages":"0.8.9","published_year":1993},
{"author":"Gizela","book_name":"Bear, polar","pages":"0.7.2","published_year":2004},
{"author":"Ula","book_name":"Ring-tailed possum","pages":"0.94","published_year":1992},
{"author":"Honey","book_name":"Common grenadier","pages":"0.3.3","published_year":2008},
{"author":"Odille","book_name":"Red-tailed phascogale","pages":"0.41","published_year":1992},
{"author":"Druci","book_name":"African lion","pages":"9.04","published_year":2003},
{"author":"Blake","book_name":"Wallaroo, common","pages":"0.34","published_year":1992},
{"author":"Sauveur","book_name":"Teal, hottentot","pages":"8.9","published_year":1992},
{"author":"Eba","book_name":"Peregrine falcon","pages":"0.8.7","published_year":2012},
{"author":"Dall","book_name":"Bare-faced go away bird","pages":"0.87","published_year":2003},
{"author":"Nealon","book_name":"Three-banded plover","pages":"0.7.9","published_year":1994},
{"author":"Donovan","book_name":"Greylag goose","pages":"0.43","published_year":2011},
{"author":"Joe","book_name":"Tree porcupine","pages":"0.12","published_year":2010},
{"author":"Philippe","book_name":"Starling, red-shouldered glossy","pages":"0.42","published_year":2003},
{"author":"Bernice","book_name":"Squirrel, pine","pages":"0.5.9","published_year":1997},
{"author":"Adey","book_name":"Malachite kingfisher","pages":"6.55","published_year":1985},
{"author":"Solly","book_name":"Indian jackal","pages":"2.98","published_year":2011},
{"author":"Marianna","book_name":"White rhinoceros","pages":"8.48","published_year":2000},
{"author":"Hans","book_name":"Monitor, two-banded","pages":"0.74","published_year":2004},
{"author":"Svend","book_name":"Chestnut weaver","pages":"0.6.6","published_year":2012},
{"author":"Konstanze","book_name":"Praying mantis (unidentified)","pages":"8.3","published_year":2009},
{"author":"Lorene","book_name":"Malay squirrel (unidentified)","pages":"4.8.8","published_year":2009},
{"author":"Hally","book_name":"Buffalo, wild water","pages":"0.6.9","published_year":1994},
{"author":"Heinrick","book_name":"South American meadowlark (unidentified)","pages":"0.3.8","published_year":1998},
{"author":"Waly","book_name":"Madagascar hawk owl","pages":"0.93","published_year":2002},
{"author":"Meggi","book_name":"Mara","pages":"2.3","published_year":2001},
{"author":"Darnell","book_name":"Admiral, indian red","pages":"5.20","published_year":2007},
{"author":"Freddie","book_name":"Nile crocodile","pages":"0.2.1","published_year":2011},
{"author":"Ola","book_name":"Caracara (unidentified)","pages":"7.8","published_year":2005},
{"author":"Jerrie","book_name":"Secretary bird","pages":"4.6","published_year":2006},
{"author":"Brandi","book_name":"Sage grouse","pages":"1.3.4","published_year":2011},
{"author":"Angeline","book_name":"Three-banded plover","pages":"0.96","published_year":1993},
{"author":"Karia","book_name":"Cape cobra","pages":"5.1.7","published_year":2009},
{"author":"Danielle","book_name":"Amazon parrot (unidentified)","pages":"8.6.2","published_year":1997},
{"author":"Tonia","book_name":"Boa, malagasy ground","pages":"3.8","published_year":1988},
{"author":"Jory","book_name":"Caracal","pages":"0.21","published_year":2006},
{"author":"Kylila","book_name":"Bobcat","pages":"9.0","published_year":2010},
{"author":"Ainslee","book_name":"Gecko, bent-toed","pages":"0.7.0","published_year":2007},
{"author":"Wolf","book_name":"Bird, bare-faced go away","pages":"0.4.1","published_year":2010},
{"author":"Augusta","book_name":"Cockatoo, red-tailed","pages":"8.4.3","published_year":2005},
{"author":"Patrick","book_name":"Red-billed tropic bird","pages":"0.6.7","published_year":2011},
{"author":"Rubie","book_name":"Helmeted guinea fowl","pages":"9.86","published_year":1994},
{"author":"Kathrine","book_name":"Wolf spider","pages":"4.5.3","published_year":1993},
{"author":"Palmer","book_name":"Steenbok","pages":"5.12","published_year":2003},
{"author":"Iolande","book_name":"Southern screamer","pages":"0.7.2","published_year":2011},
{"author":"Eileen","book_name":"Northern fur seal","pages":"2.45","published_year":1998},
{"author":"Thurston","book_name":"Shrike, common boubou","pages":"0.9.8","published_year":2006},
{"author":"Cornall","book_name":"Sloth, pale-throated three-toed","pages":"9.73","published_year":1988},
{"author":"Webb","book_name":"Otter, oriental short-clawed","pages":"0.45","published_year":1999},
{"author":"Turner","book_name":"Spotted deer","pages":"5.9","published_year":1992},
{"author":"Christal","book_name":"Cape clawless otter","pages":"2.77","published_year":2011},
{"author":"Brandais","book_name":"Curlew, black","pages":"4.6.2","published_year":2003},
{"author":"Adrian","book_name":"Giant anteater","pages":"0.79","published_year":1995},
{"author":"Lucas","book_name":"Frilled dragon","pages":"1.0.4","published_year":2006},
{"author":"Sher","book_name":"Dolphin, striped","pages":"0.75","published_year":2011},
{"author":"Ewen","book_name":"Otter, african clawless","pages":"6.2","published_year":2003},
{"author":"Rodolphe","book_name":"Rabbit, eastern cottontail","pages":"9.11","published_year":1984},
{"author":"Catharina","book_name":"Glider, sugar","pages":"0.1.5","published_year":2009},
{"author":"Rosie","book_name":"Red-breasted cockatoo","pages":"3.1","published_year":2009},
{"author":"Freddie","book_name":"Jackal, indian","pages":"0.38","published_year":2010},
{"author":"Kent","book_name":"Legaan, ground","pages":"1.82","published_year":1995},
{"author":"Silvie","book_name":"Bent-toed gecko","pages":"0.96","published_year":1993},
{"author":"Lacey","book_name":"Emerald green tree boa","pages":"2.1.1","published_year":2008},
{"author":"Miof mela","book_name":"Prehensile-tailed porcupine","pages":"0.1.6","published_year":2009},
{"author":"Waiter","book_name":"Antelope, four-horned","pages":"8.16","published_year":1998},
{"author":"Kristel","book_name":"Ibex","pages":"0.62","published_year":2001},
{"author":"Elie","book_name":"Stork, white-necked","pages":"0.61","published_year":1996},
{"author":"Flore","book_name":"Galapagos penguin","pages":"8.7.6","published_year":2008},
{"author":"Liv","book_name":"Australian masked owl","pages":"0.2.0","published_year":2007},
{"author":"Lillian","book_name":"Cockatoo, red-tailed","pages":"8.61","published_year":2011},
{"author":"Lillis","book_name":"Egret, snowy","pages":"8.2","published_year":1995},
{"author":"Shepperd","book_name":"European badger","pages":"7.6.7","published_year":1995},
{"author":"Niki","book_name":"Gray rhea","pages":"6.5","published_year":2003},
{"author":"Krystal","book_name":"Asian water buffalo","pages":"2.5.2","published_year":2013},
{"author":"Sybila","book_name":"Eastern grey kangaroo","pages":"0.83","published_year":2000},
{"author":"Meta","book_name":"Lion, steller sea","pages":"0.82","published_year":1992},
{"author":"Linnie","book_name":"Duck, comb","pages":"9.30","published_year":2002},
{"author":"Stinky","book_name":"Racer, blue","pages":"0.97","published_year":2001},
{"author":"Berte","book_name":"Egyptian goose","pages":"2.61","published_year":1999},
{"author":"Arron","book_name":"Waterbuck, common","pages":"3.9","published_year":1999},
{"author":"Killy","book_name":"Cape Barren goose","pages":"0.16","published_year":1995},
{"author":"Dorothea","book_name":"Western palm tanager (unidentified)","pages":"0.43","published_year":1995},
{"author":"Francine","book_name":"Roseat flamingo","pages":"3.8.6","published_year":1996},
{"author":"Darcey","book_name":"Long-tailed spotted cat","pages":"2.9.4","published_year":2003},
{"author":"Daveta","book_name":"Large cormorant","pages":"5.3","published_year":2009},
{"author":"Halli","book_name":"Toddy cat","pages":"2.6.0","published_year":1999},
{"author":"Rici","book_name":"Common green iguana","pages":"4.6","published_year":2002},
{"author":"Gisela","book_name":"Booby, blue-faced","pages":"0.5.2","published_year":1997},
{"author":"Charlot","book_name":"Crimson-breasted shrike","pages":"3.9","published_year":2001},
{"author":"Shae","book_name":"Goose, spur-winged","pages":"0.1.4","published_year":2010},
{"author":"Malinde","book_name":"Colobus, magistrate black","pages":"0.6.8","published_year":2011},
{"author":"Henrieta","book_name":"Barbet, black-collared","pages":"0.4.0","published_year":1998},
{"author":"Lucinda","book_name":"Opossum, american virginia","pages":"0.8.7","published_year":2006},
{"author":"Jeremie","book_name":"Crow, pied","pages":"0.6.9","published_year":2008},
{"author":"Lorens","book_name":"Penguin, galapagos","pages":"7.7.3","published_year":1992},
{"author":"Avie","book_name":"Sloth, two-toed","pages":"0.9.5","published_year":1994},
{"author":"Windy","book_name":"Black-throated butcher bird","pages":"0.5.5","published_year":2011},
{"author":"Ranice","book_name":"Red and blue macaw","pages":"0.32","published_year":1985},
{"author":"Saba","book_name":"Flamingo, lesser","pages":"7.99","published_year":2010},
{"author":"Auria","book_name":"Armadillo, nine-banded","pages":"3.12","published_year":1992},
{"author":"Paulita","book_name":"Moose","pages":"0.2.1","published_year":1991},
{"author":"Isabelita","book_name":"Dragonfly, russian","pages":"7.8","published_year":2010},
{"author":"Raymund","book_name":"Tyrant flycatcher","pages":"0.1.6","published_year":2012},
{"author":"Hamel","book_name":"Greater adjutant stork","pages":"0.11","published_year":2010},
{"author":"Tanney","book_name":"Constrictor, eastern boa","pages":"0.1.7","published_year":2006},
{"author":"Aldric","book_name":"Squirrel, eurasian red","pages":"0.5.9","published_year":2006},
{"author":"Neila","book_name":"Wolf, mexican","pages":"0.9.1","published_year":2009},
{"author":"Adorne","book_name":"Plover, three-banded","pages":"6.1","published_year":2010},
{"author":"Antone","book_name":"Shelduck, common","pages":"7.37","published_year":1992},
{"author":"Randene","book_name":"Tern, arctic","pages":"0.51","published_year":1993},
{"author":"Shepard","book_name":"Downy woodpecker","pages":"1.04","published_year":1999},
{"author":"Jimmy","book_name":"Racer snake","pages":"9.24","published_year":1998},
{"author":"Greggory","book_name":"Sockeye salmon","pages":"0.7.2","published_year":1995},
{"author":"Kiley","book_name":"Thirteen-lined squirrel","pages":"7.7","published_year":2001},
{"author":"Osbert","book_name":"Thirteen-lined squirrel","pages":"2.9.9","published_year":1997},
{"author":"Tessi","book_name":"Chestnut weaver","pages":"3.6.7","published_year":2011},
{"author":"Flory","book_name":"Alligator, american","pages":"0.7.9","published_year":2008},
{"author":"Emyle","book_name":"Flycatcher, tyrant","pages":"0.84","published_year":1992},
{"author":"Trevor","book_name":"Gonolek, burchell's","pages":"8.87","published_year":1992},
{"author":"Ted","book_name":"Ostrich","pages":"7.9.4","published_year":2002},
{"author":"Von","book_name":"Gray heron","pages":"0.7.2","published_year":1992},
{"author":"Sadie","book_name":"Civet cat","pages":"5.9","published_year":1996},
{"author":"Claude","book_name":"Barrows goldeneye","pages":"0.40","published_year":2010},
{"author":"Orville","book_name":"Woodcock, american","pages":"0.21","published_year":1994},
{"author":"Rana","book_name":"Baboon, savanna","pages":"5.6","published_year":2003},
{"author":"Ula","book_name":"Black-throated cardinal","pages":"5.74","published_year":1996},
{"author":"Florida","book_name":"Bat, madagascar fruit","pages":"9.8","published_year":1995},
{"author":"Sonni","book_name":"Lizard, giant girdled","pages":"1.92","published_year":1989},
{"author":"Sully","book_name":"Sheathbill, snowy","pages":"0.2.7","published_year":1997},
{"author":"Mikol","book_name":"Flycatcher, tyrant","pages":"1.5.9","published_year":1999},
{"author":"Gerrie","book_name":"Cockatoo, red-breasted","pages":"0.1.5","published_year":2009},
{"author":"Mari","book_name":"Gemsbok","pages":"0.47","published_year":2006},
{"author":"Babbette","book_name":"Little brown dove","pages":"0.43","published_year":1992},
{"author":"Evelyn","book_name":"Lily trotter","pages":"7.37","published_year":1994},
{"author":"Millard","book_name":"Long-billed corella","pages":"0.4.6","published_year":1996},
{"author":"Chere","book_name":"Asian water dragon","pages":"8.84","published_year":1992},
{"author":"Melanie","book_name":"Cat, african wild","pages":"0.97","published_year":2003},
{"author":"Gerta","book_name":"Legaan, ground","pages":"5.7.8","published_year":1994},
{"author":"Moreen","book_name":"Fat-tailed dunnart","pages":"4.7.7","published_year":2005},
{"author":"Julina","book_name":"Gull, kelp","pages":"6.64","published_year":1999},
{"author":"Gill","book_name":"Cape Barren goose","pages":"2.0","published_year":2007},
{"author":"Humbert","book_name":"Sparrow, house","pages":"2.9","published_year":2006},
{"author":"Bernice","book_name":"Greater flamingo","pages":"0.53","published_year":2009},
{"author":"Ives","book_name":"Bird, black-throated butcher","pages":"0.4.6","published_year":1991},
{"author":"Adolphus","book_name":"Lemming, arctic","pages":"0.67","published_year":1985},
{"author":"Samuele","book_name":"Rabbit, eastern cottontail","pages":"2.59","published_year":2002},
{"author":"Joella","book_name":"Otter, canadian river","pages":"0.5.9","published_year":1997},
{"author":"Fairfax","book_name":"Short-beaked echidna","pages":"0.4.5","published_year":1988},
{"author":"Gaile","book_name":"Snow goose","pages":"5.7.6","published_year":1998},
{"author":"Danny","book_name":"Comb duck","pages":"8.4.1","published_year":1993},
{"author":"Cynthia","book_name":"Common long-nosed armadillo","pages":"2.4","published_year":2010},
{"author":"Jenn","book_name":"Otter, brazilian","pages":"6.4","published_year":2011},
{"author":"Burl","book_name":"Brown brocket","pages":"6.04","published_year":1994},
{"author":"Cathrine","book_name":"Dove, galapagos","pages":"0.70","published_year":2002},
{"author":"Iormina","book_name":"Iguana, common green","pages":"9.1.1","published_year":1992},
{"author":"Gerard","book_name":"Cormorant (unidentified)","pages":"0.2.3","published_year":1995},
{"author":"Aguie","book_name":"Bear, sloth","pages":"0.51","published_year":1994},
{"author":"Lula","book_name":"Dove, white-winged","pages":"6.52","published_year":2005},
{"author":"Reinald","book_name":"Red howler monkey","pages":"0.21","published_year":2003},
{"author":"Granville","book_name":"Dusky rattlesnake","pages":"3.5.4","published_year":1995},
{"author":"Michele","book_name":"Salmon, sockeye","pages":"0.87","published_year":1999},
{"author":"Keriann","book_name":"Glossy ibis","pages":"0.18","published_year":2012},
{"author":"Sloan","book_name":"Genet, small-spotted","pages":"0.64","published_year":1994},
{"author":"Ram","book_name":"Long-billed corella","pages":"5.35","published_year":2005},
{"author":"Quintina","book_name":"Crane, stanley","pages":"2.77","published_year":1992},
{"author":"Georges","book_name":"Black-tailed deer","pages":"4.82","published_year":2005},
{"author":"Eldon","book_name":"Weaver, red-billed buffalo","pages":"0.7.1","published_year":2003},
{"author":"Wilden","book_name":"Cereopsis goose","pages":"4.7.7","published_year":1999},
{"author":"Jsandye","book_name":"Malleefowl","pages":"1.8.1","published_year":1994},
{"author":"Melisse","book_name":"White-bellied sea eagle","pages":"0.2.0","published_year":2011},
{"author":"Cinderella","book_name":"Seal, harbor","pages":"5.9.7","published_year":1986},
{"author":"Niven","book_name":"Black swan","pages":"1.7","published_year":2001},
{"author":"Talyah","book_name":"Blue crane","pages":"0.31","published_year":2008},
{"author":"Temp","book_name":"Crested barbet","pages":"0.59","published_year":1997},
{"author":"Allayne","book_name":"Penguin, galapagos","pages":"2.80","published_year":1998},
{"author":"Edgardo","book_name":"Land iguana","pages":"0.2.7","published_year":2004},
{"author":"Guilbert","book_name":"Rhea, common","pages":"6.67","published_year":1998},
{"author":"Bernadine","book_name":"Caracal","pages":"8.7","published_year":2004},
{"author":"Wakefield","book_name":"Red squirrel","pages":"0.1.5","published_year":1996},
{"author":"Rosemarie","book_name":"Common genet","pages":"1.3","published_year":2007},
{"author":"Aurie","book_name":"Giant girdled lizard","pages":"6.08","published_year":2008},
{"author":"Micki","book_name":"Eastern white pelican","pages":"3.26","published_year":2004},
{"author":"Jim","book_name":"Common wolf","pages":"7.2.3","published_year":2007},
{"author":"Tressa","book_name":"Red-billed hornbill","pages":"2.1.0","published_year":2000},
{"author":"Jerrie","book_name":"Wildebeest, blue","pages":"8.0","published_year":2006},
{"author":"Steward","book_name":"Bahama pintail","pages":"0.84","published_year":2010},
{"author":"Morey","book_name":"Dove, laughing","pages":"9.8","published_year":2007},
{"author":"Harri","book_name":"Cape clawless otter","pages":"0.76","published_year":2001},
{"author":"Maribeth","book_name":"Rhesus monkey","pages":"0.3.9","published_year":1987},
{"author":"Cirstoforo","book_name":"Paradoxure","pages":"6.3.5","published_year":2008},
{"author":"Yale","book_name":"Civet (unidentified)","pages":"3.08","published_year":1995},
{"author":"Peggy","book_name":"Stork, openbill","pages":"0.3.1","published_year":1999},
{"author":"Timmie","book_name":"Brocket, red","pages":"0.75","published_year":1997},
{"author":"Whit","book_name":"Marshbird, brown and yellow","pages":"0.28","published_year":2005},
{"author":"Ari","book_name":"Fox, silver-backed","pages":"0.2.3","published_year":2000},
{"author":"Kati","book_name":"Thirteen-lined squirrel","pages":"3.2","published_year":1999},
{"author":"Tommy","book_name":"Buffalo, asian water","pages":"0.39","published_year":2001},
{"author":"Raymund","book_name":"Knob-nosed goose","pages":"0.8.9","published_year":2008},
{"author":"Hercules","book_name":"Otter, north american river","pages":"9.65","published_year":1986},
{"author":"Selma","book_name":"Indian tree pie","pages":"0.94","published_year":1998},
{"author":"Nigel","book_name":"North American river otter","pages":"0.68","published_year":1993},
{"author":"Sigismundo","book_name":"Rufous tree pie","pages":"4.8","published_year":1990},
{"author":"Johanna","book_name":"Savanna baboon","pages":"0.6.6","published_year":1998},
{"author":"Carl","book_name":"Iguana, common green","pages":"0.33","published_year":2004},
{"author":"Fiona","book_name":"Opossum, american virginia","pages":"5.4","published_year":2008},
{"author":"Dasya","book_name":"Wild turkey","pages":"2.4.5","published_year":2002},
{"author":"Herold","book_name":"Tortoise, desert","pages":"6.1.8","published_year":2009},
{"author":"Lanie","book_name":"Sacred ibis","pages":"0.5.3","published_year":1998},
{"author":"Margareta","book_name":"Rhinoceros, black","pages":"0.23","published_year":2013},
{"author":"Tamqrah","book_name":"Cat, miner's","pages":"4.68","published_year":2010},
{"author":"Dulcine","book_name":"Plover, blacksmith","pages":"2.0","published_year":1993},
{"author":"Martie","book_name":"Hawk-eagle, crowned","pages":"0.6.7","published_year":2011},
{"author":"Janie","book_name":"Rhea, common","pages":"6.8","published_year":2003},
{"author":"Vivien","book_name":"Ant (unidentified)","pages":"3.8","published_year":1997},
{"author":"Isacco","book_name":"Blue waxbill","pages":"0.8.5","published_year":1992},
{"author":"Zsa zsa","book_name":"Monkey, vervet","pages":"0.76","published_year":1997},
{"author":"Todd","book_name":"Genoveva","pages":"3.5.6","published_year":2007},
{"author":"Junie","book_name":"Sheep, stone","pages":"8.7.6","published_year":2001},
{"author":"Consuela","book_name":"Armadillo, common long-nosed","pages":"0.5.2","published_year":1986},
{"author":"Anica","book_name":"Brocket, red","pages":"8.3.0","published_year":2002},
{"author":"Sofie","book_name":"Cliffchat, mocking","pages":"0.8.9","published_year":1998},
{"author":"Veronique","book_name":"African pied wagtail","pages":"4.6","published_year":1987},
{"author":"Deana","book_name":"Dik, kirk's dik","pages":"0.2.3","published_year":2001},
{"author":"Duane","book_name":"Swan, black","pages":"9.00","published_year":2002},
{"author":"Mureil","book_name":"Chacma baboon","pages":"9.39","published_year":2009},
{"author":"Bertrando","book_name":"Marten, american","pages":"4.4.0","published_year":2008},
{"author":"Ara","book_name":"Hawk-eagle, crowned","pages":"6.14","published_year":1999},
{"author":"Valerye","book_name":"Rhesus macaque","pages":"8.61","published_year":2009},
{"author":"Karry","book_name":"Common wombat","pages":"5.1.6","published_year":2011},
{"author":"Amalea","book_name":"Deer, mule","pages":"1.54","published_year":2012},
{"author":"Jillie","book_name":"Asian false vampire bat","pages":"9.5.5","published_year":2008},
{"author":"Loise","book_name":"Drongo, fork-tailed","pages":"0.22","published_year":2008},
{"author":"Conrado","book_name":"Gray heron","pages":"5.9","published_year":1991},
{"author":"Garwin","book_name":"King vulture","pages":"4.9.0","published_year":2007},
{"author":"Aubrie","book_name":"Lemur, brown","pages":"0.76","published_year":1990},
{"author":"Marlo","book_name":"Eland, common","pages":"9.8.9","published_year":1963},
{"author":"Maison","book_name":"Bustard, denham's","pages":"3.8","published_year":2005},
{"author":"Melloney","book_name":"Bunting, crested","pages":"0.90","published_year":2006},
{"author":"Gianni","book_name":"Sloth, two-toed","pages":"0.5.2","published_year":1993},
{"author":"Oliviero","book_name":"Brown pelican","pages":"7.7.4","published_year":2011},
{"author":"Latrena","book_name":"Andean goose","pages":"0.46","published_year":1998},
{"author":"Benji","book_name":"Flicker, campo","pages":"0.1.0","published_year":2006},
{"author":"Damien","book_name":"Bee-eater, white-fronted","pages":"6.76","published_year":1994},
{"author":"Helsa","book_name":"Gazer, sun","pages":"5.7","published_year":2007},
{"author":"Vitia","book_name":"Mexican beaded lizard","pages":"3.2","published_year":2009},
{"author":"Phillip","book_name":"Pale-throated three-toed sloth","pages":"2.86","published_year":1995},
{"author":"Liam","book_name":"Raven, cape","pages":"0.5.9","published_year":1996},
{"author":"Weylin","book_name":"Blue-breasted cordon bleu","pages":"7.6","published_year":1990},
{"author":"Sher","book_name":"Prairie falcon","pages":"5.0.8","published_year":1998},
{"author":"Whit","book_name":"Crane, stanley","pages":"4.6.0","published_year":2002},
{"author":"Raquel","book_name":"Eastern fox squirrel","pages":"3.6.4","published_year":2008},
{"author":"Una","book_name":"Asian water dragon","pages":"5.6","published_year":2009},
{"author":"Katey","book_name":"Dunnart, fat-tailed","pages":"0.7.6","published_year":1966},
{"author":"Allie","book_name":"Snake (unidentified)","pages":"0.6.4","published_year":2012},
{"author":"Lettie","book_name":"Eagle, white-bellied sea","pages":"7.26","published_year":1993},
{"author":"Nadeen","book_name":"Vulture, egyptian","pages":"1.9.6","published_year":1969},
{"author":"Mano","book_name":"Crane, sarus","pages":"4.12","published_year":1995},
{"author":"Rani","book_name":"Duck, blue","pages":"0.7.9","published_year":2004},
{"author":"Audra","book_name":"Cockatoo, long-billed","pages":"5.8","published_year":2011},
{"author":"Hilarius","book_name":"Moorhen, purple","pages":"3.5","published_year":1993},
{"author":"Arlie","book_name":"Wallaby, red-necked","pages":"1.10","published_year":2008},
{"author":"Cristy","book_name":"Killer whale","pages":"3.35","published_year":1965},
{"author":"Mycah","book_name":"Marabou stork","pages":"6.3.8","published_year":1993},
{"author":"Cathee","book_name":"Stanley crane","pages":"8.6.1","published_year":2002},
{"author":"Justina","book_name":"Crane, blue","pages":"0.2.5","published_year":1985},
{"author":"Benny","book_name":"Common grenadier","pages":"0.4.2","published_year":2005},
{"author":"Obadias","book_name":"Three-banded plover","pages":"0.5.1","published_year":2000},
{"author":"Daron","book_name":"Tapir, brazilian","pages":"2.75","published_year":1993},
{"author":"Kacie","book_name":"Little cormorant","pages":"5.4","published_year":1996},
{"author":"Kate","book_name":"Tortoise, asian foreset","pages":"4.65","published_year":2007},
{"author":"Deanne","book_name":"Sparrow, house","pages":"9.47","published_year":2002},
{"author":"Erek","book_name":"Mexican beaded lizard","pages":"0.45","published_year":1987},
{"author":"Odie","book_name":"Swamp deer","pages":"2.3.7","published_year":2002},
{"author":"Luis","book_name":"Secretary bird","pages":"0.9.7","published_year":1995},
{"author":"Briggs","book_name":"Lark, horned","pages":"0.17","published_year":2002},
{"author":"Moll","book_name":"Booby, blue-footed","pages":"0.9.4","published_year":1997},
{"author":"Veronique","book_name":"Painted stork","pages":"9.63","published_year":2010},
{"author":"Immanuel","book_name":"Crab (unidentified)","pages":"0.34","published_year":2011},
{"author":"Rycca","book_name":"Possum, ring-tailed","pages":"0.3.7","published_year":2004},
{"author":"Harley","book_name":"Amazon parrot (unidentified)","pages":"2.17","published_year":1997},
{"author":"Stafford","book_name":"Goanna lizard","pages":"1.59","published_year":1998},
{"author":"Gaby","book_name":"Black-throated butcher bird","pages":"8.4","published_year":2000},
{"author":"Zebulon","book_name":"Hummingbird (unidentified)","pages":"9.70","published_year":2011},
{"author":"Tybi","book_name":"Asian water buffalo","pages":"2.9.5","published_year":2007},
{"author":"Shannen","book_name":"Brolga crane","pages":"5.5.7","published_year":1994},
{"author":"Daveta","book_name":"Lava gull","pages":"8.1.6","published_year":2002},
{"author":"Conn","book_name":"Common dolphin","pages":"8.26","published_year":1998},
{"author":"Leonore","book_name":"Magellanic penguin","pages":"0.9.7","published_year":2007},
{"author":"Ravid","book_name":"Eastern fox squirrel","pages":"0.59","published_year":2003},
{"author":"Lexine","book_name":"Four-striped grass mouse","pages":"0.7.7","published_year":2009},
{"author":"Merl","book_name":"Giant anteater","pages":"0.8.1","published_year":2006},
{"author":"Carolyne","book_name":"North American red fox","pages":"8.0.4","published_year":2001},
{"author":"Rosalinda","book_name":"Brush-tailed rat kangaroo","pages":"4.4","published_year":2001},
{"author":"Billye","book_name":"Ring-tailed coatimundi","pages":"2.17","published_year":2005},
{"author":"Kakalina","book_name":"Bear, grizzly","pages":"4.43","published_year":1994},
{"author":"Eleanora","book_name":"Egyptian cobra","pages":"2.42","published_year":2004},
{"author":"Birk","book_name":"Roseat flamingo","pages":"2.97","published_year":2010},
{"author":"Darcee","book_name":"Steller's sea lion","pages":"4.4.2","published_year":1990},
{"author":"Robbi","book_name":"Wolf spider","pages":"0.21","published_year":1963},
{"author":"Barbey","book_name":"White-cheeked pintail","pages":"0.6.4","published_year":1995},
{"author":"Jamaal","book_name":"Crow, house","pages":"0.68","published_year":1993},
{"author":"Fanni","book_name":"Colobus, black and white","pages":"1.5.4","published_year":1999},
{"author":"Karon","book_name":"Small Indian mongoose","pages":"2.45","published_year":2008},
{"author":"Grier","book_name":"Gray duiker","pages":"7.84","published_year":1993},
{"author":"Nester","book_name":"White-throated toucan","pages":"3.0.2","published_year":2007},
{"author":"Valerye","book_name":"Red-capped cardinal","pages":"0.64","published_year":2012},
{"author":"Immanuel","book_name":"Warthog","pages":"1.65","published_year":1999},
{"author":"Arni","book_name":"Bear, black","pages":"7.89","published_year":1995},
{"author":"Romain","book_name":"Dusky gull","pages":"1.50","published_year":2001},
{"author":"Clair","book_name":"Crane, sarus","pages":"8.55","published_year":1992},
{"author":"Mort","book_name":"Raccoon, common","pages":"2.7","published_year":1995},
{"author":"Verina","book_name":"Madagascar fruit bat","pages":"0.7.4","published_year":2008},
{"author":"Terrance","book_name":"Macaw, green-winged","pages":"4.5","published_year":2008},
{"author":"Bertha","book_name":"Whip-tailed wallaby","pages":"0.48","published_year":1993},
{"author":"Aubree","book_name":"Great egret","pages":"6.2.3","published_year":1999},
{"author":"Elka","book_name":"Black-tailed prairie dog","pages":"0.3.6","published_year":2011},
{"author":"Sheena","book_name":"Kalahari scrub robin","pages":"0.35","published_year":1993},
{"author":"Bat","book_name":"Sportive lemur","pages":"0.5.1","published_year":2004},
{"author":"Rawley","book_name":"Tern, arctic","pages":"1.0.3","published_year":2004},
{"author":"Florence","book_name":"Quail, gambel's","pages":"0.40","published_year":2012},
{"author":"Bondy","book_name":"Four-striped grass mouse","pages":"6.6.7","published_year":1985},
{"author":"Mariam","book_name":"Pied cormorant","pages":"3.2","published_year":1994},
{"author":"Creighton","book_name":"Rabbit, eastern cottontail","pages":"0.16","published_year":1994},
{"author":"Ganny","book_name":"Eagle, african fish","pages":"7.2","published_year":1975},
{"author":"Angelia","book_name":"Pampa gray fox","pages":"0.72","published_year":2009},
{"author":"Moira","book_name":"Magnificent frigate bird","pages":"7.57","published_year":1999},
{"author":"Skylar","book_name":"Rock dove","pages":"4.9","published_year":1996},
{"author":"Meade","book_name":"Burmese black mountain tortoise","pages":"9.1","published_year":1992},
{"author":"Alfonso","book_name":"Tenrec, tailless","pages":"0.5.7","published_year":1999},
{"author":"Emelina","book_name":"Gecko (unidentified)","pages":"7.7.0","published_year":2002},
{"author":"Tyrus","book_name":"Lorikeet, scaly-breasted","pages":"0.2.4","published_year":1997},
{"author":"Shaina","book_name":"Screamer, crested","pages":"6.83","published_year":1988},
{"author":"Auberon","book_name":"Fox, silver-backed","pages":"2.5.0","published_year":2002},
{"author":"Sonnnie","book_name":"Euro wallaby","pages":"6.22","published_year":1993},
{"author":"Sayres","book_name":"Zorro, common","pages":"0.1.8","published_year":2000},
{"author":"Langsdon","book_name":"Dove, mourning collared","pages":"3.9","published_year":2011},
{"author":"Keane","book_name":"Wallaroo, common","pages":"9.48","published_year":2005},
{"author":"Charla","book_name":"Rat, white-faced tree","pages":"7.1.0","published_year":2008},
{"author":"Caitrin","book_name":"Woodpecker, downy","pages":"5.1.7","published_year":1999},
{"author":"Chrysa","book_name":"Macaw, green-winged","pages":"2.9.1","published_year":1998},
{"author":"Sinclare","book_name":"Gecko, ring-tailed","pages":"3.0","published_year":1993},
{"author":"Edan","book_name":"Otter, small-clawed","pages":"0.42","published_year":1992},
{"author":"Neysa","book_name":"Blue peacock","pages":"0.67","published_year":1997},
{"author":"Ephrayim","book_name":"Pampa gray fox","pages":"9.5.6","published_year":1999},
{"author":"Dorisa","book_name":"Shark, blue","pages":"0.4.4","published_year":1990},
{"author":"Christi","book_name":"South American meadowlark (unidentified)","pages":"9.97","published_year":2011},
{"author":"Tandie","book_name":"Racer, blue","pages":"2.0","published_year":2011},
{"author":"Cherilynn","book_name":"Parrot, hawk-headed","pages":"0.87","published_year":1997},
{"author":"Lenette","book_name":"Savannah deer","pages":"0.4.0","published_year":1989},
{"author":"Erena","book_name":"Tinamou, elegant crested","pages":"7.38","published_year":1992},
{"author":"Blake","book_name":"Mississippi alligator","pages":"0.4.1","published_year":1997},
{"author":"Markus","book_name":"Kingfisher, pied","pages":"0.3.1","published_year":2006},
{"author":"Grissel","book_name":"Gerenuk","pages":"0.30","published_year":2012},
{"author":"Ingaborg","book_name":"Gulls (unidentified)","pages":"0.13","published_year":2006},
{"author":"Freda","book_name":"Eland, common","pages":"0.5.8","published_year":2011},
{"author":"Sada","book_name":"Penguin, magellanic","pages":"0.4.2","published_year":2001},
{"author":"Annie","book_name":"American buffalo","pages":"5.3","published_year":2005},
{"author":"Tiff","book_name":"Bird, pied butcher","pages":"7.33","published_year":2001},
{"author":"Lottie","book_name":"Pintail, bahama","pages":"7.5","published_year":2001},
{"author":"Faustina","book_name":"Cape white-eye","pages":"0.82","published_year":2001},
{"author":"Correy","book_name":"Yellow-necked spurfowl","pages":"4.2.8","published_year":1990},
{"author":"Kristin","book_name":"Echidna, short-beaked","pages":"1.5","published_year":1992},
{"author":"Tamqrah","book_name":"Caribou","pages":"5.23","published_year":2003},
{"author":"Perkin","book_name":"Skimmer, four-spotted","pages":"0.63","published_year":2001},
{"author":"Jermaine","book_name":"Whale, killer","pages":"5.94","published_year":2011},
{"author":"Virgilio","book_name":"Jaguar","pages":"0.56","published_year":1987},
{"author":"Gaby","book_name":"Australian masked owl","pages":"0.7.2","published_year":2005},
{"author":"Dani","book_name":"Bushbuck","pages":"1.78","published_year":1985},
{"author":"Leyla","book_name":"Barasingha deer","pages":"2.5","published_year":1999},
{"author":"Roselia","book_name":"Cormorant, neotropic","pages":"2.98","published_year":1993},
{"author":"Hillery","book_name":"Crowned hawk-eagle","pages":"2.29","published_year":1995},
{"author":"Thain","book_name":"Woolly-necked stork","pages":"0.3.8","published_year":2007},
{"author":"Latia","book_name":"Southern screamer","pages":"2.4.3","published_year":2006},
{"author":"Thomasina","book_name":"Brown capuchin","pages":"8.9","published_year":2003},
{"author":"Anastasia","book_name":"White-winged black tern","pages":"8.9","published_year":1989},
{"author":"Saxe","book_name":"Peccary, white-lipped","pages":"3.42","published_year":2002},
{"author":"Patti","book_name":"Jackrabbit, white-tailed","pages":"0.51","published_year":2010},
{"author":"Aleece","book_name":"Ox, musk","pages":"0.82","published_year":2002},
{"author":"Giffard","book_name":"Goanna lizard","pages":"3.6","published_year":2005},
{"author":"Josefina","book_name":"Heron, giant","pages":"5.5.4","published_year":2011},
{"author":"Urbano","book_name":"Oryx, fringe-eared","pages":"0.56","published_year":2003},
{"author":"Elianore","book_name":"Raccoon, crab-eating","pages":"3.0.7","published_year":1994},
{"author":"Benji","book_name":"Crested screamer","pages":"0.2.0","published_year":1984},
{"author":"Morrie","book_name":"Little heron","pages":"0.5.1","published_year":2004},
{"author":"Tiertza","book_name":"Eurasian hoopoe","pages":"7.66","published_year":2003},
{"author":"Alford","book_name":"Wood pigeon","pages":"2.5.1","published_year":2012},
{"author":"Crin","book_name":"Elk, Wapiti","pages":"8.50","published_year":2000},
{"author":"Ursa","book_name":"Roadrunner, greater","pages":"0.50","published_year":2000},
{"author":"Stephana","book_name":"Moorhen, purple","pages":"0.76","published_year":2003},
{"author":"Sioux","book_name":"Cormorant, large","pages":"0.57","published_year":2010},
{"author":"Kevina","book_name":"Blue catfish","pages":"0.5.5","published_year":1989},
{"author":"Perry","book_name":"Bird, red-billed tropic","pages":"8.3","published_year":1992},
{"author":"Finn","book_name":"Glider, sugar","pages":"0.8.9","published_year":2011},
{"author":"Mirna","book_name":"Barbet, levaillant's","pages":"6.6","published_year":2010},
{"author":"Donnajean","book_name":"Bent-toed gecko","pages":"7.5.6","published_year":2003},
{"author":"Sigfrid","book_name":"Leopard","pages":"0.81","published_year":2003},
{"author":"Fairleigh","book_name":"Raccoon, common","pages":"2.2.8","published_year":2009},
{"author":"Gene","book_name":"Malachite kingfisher","pages":"3.2.3","published_year":2000},
{"author":"Ira","book_name":"Goose, canada","pages":"5.2.5","published_year":2000},
{"author":"Allegra","book_name":"Southern white-crowned shrike","pages":"6.40","published_year":1986},
{"author":"Maud","book_name":"Polecat, african","pages":"5.3","published_year":1989},
{"author":"Dallis","book_name":"Ring-tailed lemur","pages":"2.64","published_year":1987},
{"author":"Ki","book_name":"Agama lizard (unidentified)","pages":"0.61","published_year":1983},
{"author":"Ansel","book_name":"Downy woodpecker","pages":"8.4.2","published_year":2008},
{"author":"Emelen","book_name":"Greater adjutant stork","pages":"0.81","published_year":1991},
{"author":"Martina","book_name":"Viper, egyptian","pages":"9.46","published_year":2009},
{"author":"Demott","book_name":"Kelp gull","pages":"6.0","published_year":2008},
{"author":"Greg","book_name":"Pelican, australian","pages":"8.68","published_year":1995},
{"author":"Sharia","book_name":"Flamingo, chilean","pages":"8.22","published_year":1995},
{"author":"Rivkah","book_name":"Red-headed woodpecker","pages":"0.58","published_year":1993},
{"author":"Skyler","book_name":"Lizard, desert spiny","pages":"3.9","published_year":1999},
{"author":"Sheilah","book_name":"Lemur, sportive","pages":"6.27","published_year":1999},
{"author":"Odell","book_name":"European spoonbill","pages":"6.5","published_year":1994},
{"author":"Dinah","book_name":"Barbet, crested","pages":"2.9.0","published_year":1987},
{"author":"Lora","book_name":"Flicker, campo","pages":"0.64","published_year":2010},
{"author":"Bathsheba","book_name":"Snowy owl","pages":"7.5","published_year":2000},
{"author":"Alvira","book_name":"Goat, mountain","pages":"5.7.2","published_year":2001},
{"author":"Herculie","book_name":"White-winged tern","pages":"0.3.0","published_year":2008},
{"author":"Goran","book_name":"Common genet","pages":"3.3.3","published_year":1996},
{"author":"Wendye","book_name":"Gray langur","pages":"1.55","published_year":1999},
{"author":"Zsa zsa","book_name":"Deer, mule","pages":"3.7","published_year":2010},
{"author":"Saundra","book_name":"Toddy cat","pages":"6.3","published_year":2001},
{"author":"Lorenzo","book_name":"Kongoni","pages":"0.1.9","published_year":2012},
{"author":"Mordy","book_name":"Wallaby, red-necked","pages":"0.9.5","published_year":2003},
{"author":"Mauricio","book_name":"Crow, house","pages":"2.8","published_year":2009},
{"author":"Gaultiero","book_name":"Whale, killer","pages":"0.66","published_year":2001},
{"author":"Irene","book_name":"Two-toed tree sloth","pages":"8.2.3","published_year":1996},
{"author":"Fredi","book_name":"Lory, rainbow","pages":"1.6.7","published_year":1966},
{"author":"Silvie","book_name":"Common rhea","pages":"1.38","published_year":1992},
{"author":"Vicki","book_name":"White-throated robin","pages":"9.0.5","published_year":2004},
{"author":"Micki","book_name":"Tsessebe","pages":"7.7","published_year":2009},
{"author":"Martita","book_name":"Fowl, helmeted guinea","pages":"7.09","published_year":2007},
{"author":"Daloris","book_name":"Campo flicker","pages":"2.5.7","published_year":2011},
{"author":"Beatrisa","book_name":"Boat-billed heron","pages":"1.78","published_year":1995},
{"author":"Carlin","book_name":"Common boubou shrike","pages":"5.38","published_year":2002},
{"author":"Sawyer","book_name":"Shelduck, common","pages":"0.68","published_year":1998},
{"author":"Rob","book_name":"Phalarope, red-necked","pages":"0.58","published_year":1998},
{"author":"Erwin","book_name":"Kingfisher, white-throated","pages":"0.6.1","published_year":1985},
{"author":"Webb","book_name":"Red squirrel","pages":"4.5.5","published_year":2006},
{"author":"Silvana","book_name":"Crocodile, nile","pages":"8.99","published_year":2010},
{"author":"Caddric","book_name":"African snake (unidentified)","pages":"6.34","published_year":2009},
{"author":"Neille","book_name":"Eagle, golden","pages":"2.95","published_year":2003},
{"author":"Ag","book_name":"African wild dog","pages":"9.4.6","published_year":2002},
{"author":"Margaret","book_name":"Tortoise, burmese black mountain","pages":"3.93","published_year":2001},
{"author":"Felipe","book_name":"Waxbill, blue","pages":"0.7.8","published_year":2011},
{"author":"Lorens","book_name":"Black-collared barbet","pages":"1.85","published_year":2004},
{"author":"Barrie","book_name":"Phalarope, grey","pages":"0.16","published_year":1993},
{"author":"Fitzgerald","book_name":"African fish eagle","pages":"4.2","published_year":1999},
{"author":"Jenifer","book_name":"Antechinus, brown","pages":"1.1","published_year":2009},
{"author":"Elihu","book_name":"Blesbok","pages":"0.6.7","published_year":2006},
{"author":"Dawn","book_name":"Giant armadillo","pages":"9.56","published_year":1985},
{"author":"Isabel","book_name":"Field flicker","pages":"0.2.7","published_year":1984},
{"author":"Lynne","book_name":"Iguana, land","pages":"0.48","published_year":1997},
{"author":"Boot","book_name":"Lemur, sportive","pages":"0.39","published_year":2002},
{"author":"Mendie","book_name":"Arctic ground squirrel","pages":"0.6.3","published_year":2006},
{"author":"Desi","book_name":"Nelson ground squirrel","pages":"0.77","published_year":2003},
{"author":"Daron","book_name":"Bettong, brush-tailed","pages":"0.53","published_year":2005},
{"author":"Dre","book_name":"Thirteen-lined squirrel","pages":"0.7.4","published_year":1998},
{"author":"Veronike","book_name":"Black-tailed prairie dog","pages":"0.1.6","published_year":1991},
{"author":"Dierdre","book_name":"Macaw, green-winged","pages":"0.8.9","published_year":1992},
{"author":"Millisent","book_name":"Hawk-headed parrot","pages":"7.2","published_year":2001},
{"author":"Del","book_name":"Cat, toddy","pages":"8.86","published_year":1992},
{"author":"Grata","book_name":"American bison","pages":"0.22","published_year":1989},
{"author":"Marillin","book_name":"Timber wolf","pages":"5.0","published_year":2006},
{"author":"Jaquenette","book_name":"Grey lourie","pages":"5.53","published_year":2003},
{"author":"Rosanne","book_name":"Phalarope, northern","pages":"2.4.0","published_year":2007},
{"author":"Pavel","book_name":"Openbill, asian","pages":"0.6.8","published_year":1995},
{"author":"Daven","book_name":"Bulbul, african red-eyed","pages":"8.9","published_year":2011},
{"author":"Sonya","book_name":"Mynah, common","pages":"0.74","published_year":2000},
{"author":"Drucie","book_name":"African bush squirrel","pages":"1.15","published_year":2006},
{"author":"Agnella","book_name":"Reedbuck, bohor","pages":"0.80","published_year":2010},
{"author":"Stanfield","book_name":"Asian water buffalo","pages":"9.48","published_year":2008},
{"author":"Ileane","book_name":"Black curlew","pages":"0.6.2","published_year":1994},
{"author":"Bondy","book_name":"Bottle-nose dolphin","pages":"9.7.4","published_year":2008},
{"author":"Randolph","book_name":"Yellow mongoose","pages":"7.4","published_year":1997},
{"author":"Feliks","book_name":"Common turkey","pages":"4.37","published_year":2008},
{"author":"Jeana","book_name":"Trumpeter, dark-winged","pages":"1.8.3","published_year":1994},
{"author":"Petr","book_name":"Common raccoon","pages":"0.75","published_year":1996},
{"author":"Zenia","book_name":"Mongoose, javan gold-spotted","pages":"8.5.8","published_year":2012},
{"author":"Ervin","book_name":"Asiatic jackal","pages":"8.09","published_year":1990},
{"author":"Seward","book_name":"White-browed sparrow weaver","pages":"0.41","published_year":1995},
{"author":"Fran","book_name":"Cat, civet","pages":"1.5","published_year":2001},
{"author":"Aili","book_name":"Snake-necked turtle","pages":"9.8.0","published_year":1988},
{"author":"Vern","book_name":"Skink, blue-tongued","pages":"5.8","published_year":1993},
{"author":"Dalli","book_name":"Herring gull","pages":"9.77","published_year":2008},
{"author":"Romeo","book_name":"Brazilian tapir","pages":"1.59","published_year":2009},
{"author":"Shea","book_name":"Yellow-rumped siskin","pages":"1.69","published_year":1994},
{"author":"Giselbert","book_name":"Penguin, fairy","pages":"0.6.9","published_year":2004},
{"author":"Camel","book_name":"Cockatoo, sulfur-crested","pages":"9.5","published_year":1998},
{"author":"Beth","book_name":"Common pheasant","pages":"6.6","published_year":2009},
{"author":"Francisca","book_name":"Brazilian otter","pages":"0.5.6","published_year":2012},
{"author":"Imelda","book_name":"Kirk's dik dik","pages":"0.31","published_year":1996},
{"author":"Blondy","book_name":"Malay squirrel (unidentified)","pages":"4.93","published_year":1992},
{"author":"Angeli","book_name":"Owl, snowy","pages":"0.35","published_year":1999},
{"author":"Adam","book_name":"Crowned hawk-eagle","pages":"1.7","published_year":1999},
{"author":"Iseabal","book_name":"Parakeet, rose-ringed","pages":"9.18","published_year":2004},
{"author":"Gennie","book_name":"Fox, savanna","pages":"0.6.6","published_year":2003},
{"author":"Karyl","book_name":"Wapiti, elk,","pages":"0.16","published_year":2006},
{"author":"Kenny","book_name":"Indian star tortoise","pages":"6.74","published_year":2004},
{"author":"Karlie","book_name":"Glossy ibis","pages":"0.6.4","published_year":1993},
{"author":"Clywd","book_name":"Stick insect","pages":"3.0","published_year":2006},
{"author":"Camile","book_name":"Green-winged trumpeter","pages":"9.08","published_year":2009},
{"author":"Sigismund","book_name":"Bennett's wallaby","pages":"9.93","published_year":1991},
{"author":"Barbe","book_name":"Common ringtail","pages":"3.2.0","published_year":2010},
{"author":"Garwin","book_name":"Raven, cape","pages":"8.24","published_year":2001},
{"author":"Madge","book_name":"Yellow-crowned night heron","pages":"3.4","published_year":2002},
{"author":"Sammy","book_name":"Red-tailed hawk","pages":"0.28","published_year":2004},
{"author":"Rivy","book_name":"Cormorant, large","pages":"0.40","published_year":1998},
{"author":"Elisabeth","book_name":"Caiman, spectacled","pages":"9.2","published_year":2002},
{"author":"Kaiser","book_name":"Cockatoo, long-billed","pages":"0.6.2","published_year":1997},
{"author":"Angela","book_name":"Mocking cliffchat","pages":"0.9.5","published_year":2000},
{"author":"Philip","book_name":"Cobra, cape","pages":"0.5.4","published_year":2005},
{"author":"Nichole","book_name":"Onager","pages":"0.8.6","published_year":1987},
{"author":"Almira","book_name":"Wolf spider","pages":"0.2.0","published_year":2007},
{"author":"Edvard","book_name":"Neotropic cormorant","pages":"1.9.4","published_year":1985},
{"author":"Abeu","book_name":"Otter, canadian river","pages":"8.3.4","published_year":2009},
{"author":"Dody","book_name":"Suricate","pages":"2.5","published_year":1991},
{"author":"Justin","book_name":"Peccary, white-lipped","pages":"8.7","published_year":2006},
{"author":"Thoma","book_name":"Green-winged macaw","pages":"5.80","published_year":2012},
{"author":"Isabelle","book_name":"Laughing kookaburra","pages":"1.20","published_year":1994},
{"author":"Liam","book_name":"Grey phalarope","pages":"0.8.9","published_year":2000},
{"author":"Clemmie","book_name":"Black swan","pages":"3.2.5","published_year":1997},
{"author":"Meta","book_name":"Eastern dwarf mongoose","pages":"0.55","published_year":2007},
{"author":"Claudianus","book_name":"Lizard, collared","pages":"3.21","published_year":1987},
{"author":"Evyn","book_name":"Sandpiper, spotted wood","pages":"0.6.9","published_year":2003},
{"author":"Gallard","book_name":"Skink, african","pages":"1.47","published_year":1997},
{"author":"Foster","book_name":"Bat-eared fox","pages":"9.0","published_year":2004},
{"author":"Lem","book_name":"Tortoise, asian foreset","pages":"0.5.1","published_year":1992},
{"author":"Nickolaus","book_name":"Lark, horned","pages":"0.97","published_year":2009},
{"author":"Joanna","book_name":"Macaque, japanese","pages":"0.17","published_year":2007},
{"author":"Dasi","book_name":"Vulture, lappet-faced","pages":"8.5","published_year":2003},
{"author":"Filide","book_name":"Knob-nosed goose","pages":"6.0","published_year":1993},
{"author":"Sula","book_name":"Indian star tortoise","pages":"0.63","published_year":1997},
{"author":"Scotti","book_name":"Moorhen, purple","pages":"2.7.4","published_year":1998},
{"author":"Brittaney","book_name":"Echidna, short-beaked","pages":"0.16","published_year":2009},
{"author":"Riobard","book_name":"Booby, blue-footed","pages":"0.7.7","published_year":2005},
{"author":"Rasla","book_name":"African snake (unidentified)","pages":"2.3","published_year":2000},
{"author":"Oralie","book_name":"Western palm tanager (unidentified)","pages":"2.7","published_year":2003},
{"author":"Alexio","book_name":"Barbet, crested","pages":"0.3.6","published_year":2007},
{"author":"Belvia","book_name":"Griffon vulture","pages":"2.2","published_year":2004},
{"author":"Ellie","book_name":"Bear, polar","pages":"0.6.7","published_year":1991},
{"author":"Tandie","book_name":"Superb starling","pages":"2.7.1","published_year":2005},
{"author":"Artair","book_name":"Common duiker","pages":"5.1","published_year":2008},
{"author":"Annis","book_name":"European badger","pages":"1.7","published_year":1995},
{"author":"Cart","book_name":"Savanna baboon","pages":"5.52","published_year":1997},
{"author":"Gunner","book_name":"Crane, blue","pages":"0.8.0","published_year":1990},
{"author":"Melina","book_name":"Puna ibis","pages":"6.55","published_year":1994},
{"author":"Johny","book_name":"Black and white colobus","pages":"0.8.4","published_year":2009},
{"author":"Kristi","book_name":"Eagle, pallas's fish","pages":"0.9.8","published_year":1998},
{"author":"Barnebas","book_name":"Iguana, land","pages":"3.4","published_year":2010},
{"author":"Wylma","book_name":"Asian water dragon","pages":"0.46","published_year":2011},
{"author":"Candice","book_name":"Herring gull","pages":"5.1","published_year":2001},
{"author":"Tedda","book_name":"Bushbuck","pages":"8.6.9","published_year":1992},
{"author":"Valery","book_name":"Grey heron","pages":"9.6.8","published_year":1987},
{"author":"Michaeline","book_name":"Thomson's gazelle","pages":"5.42","published_year":2000},
{"author":"Sibella","book_name":"Malay squirrel (unidentified)","pages":"3.9.4","published_year":1976},
{"author":"Ettie","book_name":"Goose, andean","pages":"0.8.9","published_year":1996},
{"author":"Jeramey","book_name":"Indian peacock","pages":"5.1.7","published_year":2009},
{"author":"Desmund","book_name":"Griffon vulture","pages":"7.3.8","published_year":1999},
{"author":"Tomi","book_name":"Yellow-headed caracara","pages":"9.05","published_year":1994},
{"author":"Gert","book_name":"Eurasian hoopoe","pages":"6.3","published_year":2006},
{"author":"Marcelline","book_name":"Butterfly, canadian tiger swallowtail","pages":"2.5.4","published_year":2010},
{"author":"Flynn","book_name":"Serval","pages":"0.8.9","published_year":2010},
{"author":"Pauline","book_name":"Lizard, blue-tongued","pages":"9.44","published_year":2006},
{"author":"Spike","book_name":"Jaeger, long-tailed","pages":"7.6","published_year":2002},
{"author":"Chrissy","book_name":"Insect, stick","pages":"4.4.1","published_year":2013},
{"author":"Callie","book_name":"Black and white colobus","pages":"0.91","published_year":1995},
{"author":"Caria","book_name":"Zorilla","pages":"0.7.7","published_year":1984},
{"author":"Barbe","book_name":"Roller, lilac-breasted","pages":"0.8.9","published_year":1989},
{"author":"Hildagarde","book_name":"Eagle, pallas's fish","pages":"9.4","published_year":1986}]

console.log(User_A)
   
    next()
}




app.listen(2345, ()=>{
    console.log("Listening on port 2345");
});